# Generated by Django 3.2.4 on 2021-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mypic', models.ImageField(blank=True, upload_to='uploads/images')),
                ('logo', models.ImageField(blank=True, upload_to='uploads/images')),
                ('myskills', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='uploads/images')),
                ('url', models.URLField(blank=True)),
                ('date_created', models.DateField()),
                ('platform', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
